### ISSUE TITLE
Улучшение модалки подборки (screen-interaction.html)

### ISSUE THREAD

**Issue by vladimir-shalaev22** [html5css3-pro/loreal#3]
* ~~Упростить выборку цветотипа (написать чистую функцию)~~
* ~~Вынести все данные в отдельный файл JSON~~
* ~~Убрать все лишние попапы~~
* ~~Подготовить шаблон попапа~~
* ~~Установить связь данных с попапом~~

**Comment by html5css3-pro** [comment]
прекрасно)
